import getpass
import subprocess
import keyboard
import time
import os
import pyperclip
import signal
user = getpass.getuser()
strpath = str('C:/Users/' + user + '/Desktop')
keyword = input("keyword?")
pro = subprocess.Popen("S:\\BRANDON'S IMPORTANT DOC'S TO SHARE\\Agent Ransack\\AgentRansack.exe")
time.sleep(3)
keyboard.press_and_release('tab')
time.sleep(1)
keyboard.write('"' + keyword + '"')
time.sleep(1)
keyboard.press_and_release('tab')
time.sleep(1)
keyboard.write('S:\LOCATES')
keyboard.press_and_release('tab')
time.sleep(.25)
keyboard.press_and_release('tab')
time.sleep(.25)
keyboard.press_and_release('tab')
time.sleep(.25)
keyboard.press_and_release('tab')
time.sleep(.25)
keyboard.press_and_release('tab')
time.sleep(.25)
keyboard.press_and_release('tab')
time.sleep(.25)
keyboard.press_and_release('tab')
time.sleep(.25)
keyboard.press_and_release('tab')
time.sleep(.25)
keyboard.press_and_release('tab')
time.sleep(.25)
keyboard.press_and_release('tab')
time.sleep(.25)
keyboard.press_and_release('tab')
time.sleep(.25)
keyboard.press_and_release('tab')
time.sleep(.25)
keyboard.press_and_release('tab')
time.sleep(.25)
keyboard.press_and_release('tab')
time.sleep(.25)
keyboard.press_and_release('tab')
time.sleep(.25)
keyboard.press_and_release('tab')
time.sleep(.25)
keyboard.press_and_release('tab')
time.sleep(.25)
keyboard.press_and_release('enter')
time.sleep(20)
keyboard.press_and_release('ctrl + a')
time.sleep(3)
keyboard.press_and_release('shift + F10')
time.sleep(3)
keyboard.press_and_release('down')
time.sleep(1)
keyboard.press_and_release('down')
time.sleep(1)
keyboard.press_and_release('enter')
time.sleep(2)
filelist = open(strpath +'/FILES.xls', 'a')
time.sleep(2)
content = pyperclip.paste()
time.sleep(4)
filelist.write(content)
time.sleep(2)
subprocess.Popen.kill(pro)
