# -*- coding: cp1252 -*-

import os,sys
os.rename('C:/Users/brandonh/Desktop/Pretreatment Inspections/10100 Mukilteo Speedway 100','C:/Users/brandonh/Desktop/Pretreatment Inspections/STARBUCKS COFFEE_10100 Mukilteo Speedway 100')
os.rename('C:/Users/brandonh/Desktop/Pretreatment Inspections/10100 Mukilteo Speedway 106','C:/Users/brandonh/Desktop/Pretreatment Inspections/BITE OF NEW YORK_10100 Mukilteo Speedway 106')
os.rename('C:/Users/brandonh/Desktop/Pretreatment Inspections/10727 47th Pl W','C:/Users/brandonh/Desktop/Pretreatment Inspections/APPLIED AERO SYSTEMS_10727 47th Pl W')
os.rename('C:/Users/brandonh/Desktop/Pretreatment Inspections/10729 47th Av W','C:/Users/brandonh/Desktop/Pretreatment Inspections/WESMAR PRODUCTS _10729 47th Av W')
os.rename('C:/Users/brandonh/Desktop/Pretreatment Inspections/10801 Harbour Pointe Blvd','C:/Users/brandonh/Desktop/Pretreatment Inspections/KAMIAK HIGH SCHOOL_10801 Harbour Pointe Blvd')
os.rename('C:/Users/brandonh/Desktop/Pretreatment Inspections/10802 47th Av W','C:/Users/brandonh/Desktop/Pretreatment Inspections/RANE CORP_10802 47th Av W')
os.rename('C:/Users/brandonh/Desktop/Pretreatment Inspections/10809 47th Ave W','C:/Users/brandonh/Desktop/Pretreatment Inspections/CASCADE PRECISION_10809 47th Ave W')
os.rename('C:/Users/brandonh/Desktop/Pretreatment Inspections/10809 Mukilteo Speedway','C:/Users/brandonh/Desktop/Pretreatment Inspections/Lombardos_10809 Mukilteo Speedway')
os.rename('C:/Users/brandonh/Desktop/Pretreatment Inspections/10821 47th Av W A','C:/Users/brandonh/Desktop/Pretreatment Inspections/CENTARR/ELECTRICAL HUB_10821 47th Av W A')
os.rename('C:/Users/brandonh/Desktop/Pretreatment Inspections/10900 Mukilteo Speedway','C:/Users/brandonh/Desktop/Pretreatment Inspections/TAJ SANDHU MUKILTEO SHELL LLC_10900 Mukilteo Speedway')
os.rename('C:/Users/brandonh/Desktop/Pretreatment Inspections/10915 47th Av W','C:/Users/brandonh/Desktop/Pretreatment Inspections/ACCOUTREMENTS_10915 47th Av W')
os.rename('C:/Users/brandonh/Desktop/Pretreatment Inspections/10924 Mukilteo Speedway D','C:/Users/brandonh/Desktop/Pretreatment Inspections/GARLIC JIMS FAMOUS GOURMET PIZZA_10924 Mukilteo Speedway D')
os.rename('C:/Users/brandonh/Desktop/Pretreatment Inspections/10924 Mukilteo Speedway G','C:/Users/brandonh/Desktop/Pretreatment Inspections/SAKUMA JAPANESE RESTAURANT_10924 Mukilteo Speedway G')
os.rename('C:/Users/brandonh/Desktop/Pretreatment Inspections/10924 Mukilteo Speedway H-1','C:/Users/brandonh/Desktop/Pretreatment Inspections/HENRYS DONUTS_10924 Mukilteo Speedway H-1')
os.rename('C:/Users/brandonh/Desktop/Pretreatment Inspections/10924 Mukilteo Speedway H-2','C:/Users/brandonh/Desktop/Pretreatment Inspections/LOTUS CHINESE RESTAURANT_10924 Mukilteo Speedway H-2')
os.rename('C:/Users/brandonh/Desktop/Pretreatment Inspections/11012 Mukilteo Speedway','C:/Users/brandonh/Desktop/Pretreatment Inspections/ADPRO LITHO INC _11012 Mukilteo Speedway')
os.rename('C:/Users/brandonh/Desktop/Pretreatment Inspections/11015 47th Av W','C:/Users/brandonh/Desktop/Pretreatment Inspections/HYDRAMASTER NORTH AMERICA _11015 47th Av W')
os.rename('C:/Users/brandonh/Desktop/Pretreatment Inspections/11027 47th Av W','C:/Users/brandonh/Desktop/Pretreatment Inspections/NORTHWAY PRODUCTS INC_11027 47th Av W')
os.rename('C:/Users/brandonh/Desktop/Pretreatment Inspections/11100 Mukilteo Speedway','C:/Users/brandonh/Desktop/Pretreatment Inspections/PROFESSIONAL COLLISION _11100 Mukilteo Speedway')
os.rename('C:/Users/brandonh/Desktop/Pretreatment Inspections/11110 Mukilteo Speedway','C:/Users/brandonh/Desktop/Pretreatment Inspections/ACE METAL - CONST. WASTE _11110 Mukilteo Speedway')
os.rename('C:/Users/brandonh/Desktop/Pretreatment Inspections/11208 47th Av W','C:/Users/brandonh/Desktop/Pretreatment Inspections/Cub Systems_11208 47th Av W')
os.rename('C:/Users/brandonh/Desktop/Pretreatment Inspections/11215 47th Av W','C:/Users/brandonh/Desktop/Pretreatment Inspections/Workforce_11215 47th Av W')
os.rename('C:/Users/brandonh/Desktop/Pretreatment Inspections/11324 Mukilteo Speedway 3','C:/Users/brandonh/Desktop/Pretreatment Inspections/JOHNS AUTO GLASS UNLIMITED_11324 Mukilteo Speedway 3')
os.rename('C:/Users/brandonh/Desktop/Pretreatment Inspections/11324 Mukilteo Speedway 7','C:/Users/brandonh/Desktop/Pretreatment Inspections/POWDER COATING INC_11324 Mukilteo Speedway 7')
os.rename('C:/Users/brandonh/Desktop/Pretreatment Inspections/11338 Mukilteo Speedway','C:/Users/brandonh/Desktop/Pretreatment Inspections/Smart Service_11338 Mukilteo Speedway')
os.rename('C:/Users/brandonh/Desktop/Pretreatment Inspections/11338 Mukilteo Speedway B','C:/Users/brandonh/Desktop/Pretreatment Inspections/Wicked Wraps_11338 Mukilteo Speedway B')
os.rename('C:/Users/brandonh/Desktop/Pretreatment Inspections/11400 Mukilteo Speedway','C:/Users/brandonh/Desktop/Pretreatment Inspections/KARMICHAEL AUTO SALON _11400 Mukilteo Speedway')
os.rename('C:/Users/brandonh/Desktop/Pretreatment Inspections/11417 Cyrus Way 3','C:/Users/brandonh/Desktop/Pretreatment Inspections/Locknane_11417 Cyrus Way 3')
os.rename('C:/Users/brandonh/Desktop/Pretreatment Inspections/11431 Cyrus Way','C:/Users/brandonh/Desktop/Pretreatment Inspections/REDDY ICE CORPORATION_11431 Cyrus Way')
os.rename('C:/Users/brandonh/Desktop/Pretreatment Inspections/11502 Cyrus Way','C:/Users/brandonh/Desktop/Pretreatment Inspections/JUMBO FOODS INC_11502 Cyrus Way')
os.rename('C:/Users/brandonh/Desktop/Pretreatment Inspections/11524 Mukilteo Speedway 101-104','C:/Users/brandonh/Desktop/Pretreatment Inspections/Granite Transformations_11524 Mukilteo Speedway 101-104')
os.rename('C:/Users/brandonh/Desktop/Pretreatment Inspections/11524 Mukilteo Speedway 204','C:/Users/brandonh/Desktop/Pretreatment Inspections/Vartan product support_11524 Mukilteo Speedway 204')
os.rename('C:/Users/brandonh/Desktop/Pretreatment Inspections/11601 Cyrus Way 101','C:/Users/brandonh/Desktop/Pretreatment Inspections/CREATIVE BUS SALES_11601 Cyrus Way 101')
os.rename('C:/Users/brandonh/Desktop/Pretreatment Inspections/11601 Harbour Pointe Blvd 101','C:/Users/brandonh/Desktop/Pretreatment Inspections/SCOTSMAN BISTRO LLC_11601 Harbour Pointe Blvd 101')
os.rename('C:/Users/brandonh/Desktop/Pretreatment Inspections/11601 Harbour Pointe Blvd 105','C:/Users/brandonh/Desktop/Pretreatment Inspections/A burger place_11601 Harbour Pointe Blvd 105')
os.rename('C:/Users/brandonh/Desktop/Pretreatment Inspections/11609 49th Pl W','C:/Users/brandonh/Desktop/Pretreatment Inspections/TEO TECHNOLOGIES_11609 49th Pl W')
os.rename('C:/Users/brandonh/Desktop/Pretreatment Inspections/11700 Mukilteo Speedway','C:/Users/brandonh/Desktop/Pretreatment Inspections/MONGOLIAN GRILL_11700 Mukilteo Speedway')
os.rename('C:/Users/brandonh/Desktop/Pretreatment Inspections/11707 Mukilteo Speedway','C:/Users/brandonh/Desktop/Pretreatment Inspections/MUKILTEO SPEEDWAY CAFÉ_11707 Mukilteo Speedway')
os.rename('C:/Users/brandonh/Desktop/Pretreatment Inspections/11811 Mukilteo Speedway 101','C:/Users/brandonh/Desktop/Pretreatment Inspections/Mukilteo Dental Arts_11811 Mukilteo Speedway 101')
os.rename('C:/Users/brandonh/Desktop/Pretreatment Inspections/11811 Mukilteo Speedway 108','C:/Users/brandonh/Desktop/Pretreatment Inspections/Blue ribbon pet salon_11811 Mukilteo Speedway 108')
os.rename('C:/Users/brandonh/Desktop/Pretreatment Inspections/11811 Mukilteo Speedway 109','C:/Users/brandonh/Desktop/Pretreatment Inspections/Hanami_11811 Mukilteo Speedway 109')
os.rename('C:/Users/brandonh/Desktop/Pretreatment Inspections/11811 Mukilteo Speedway 110','C:/Users/brandonh/Desktop/Pretreatment Inspections/GYRO STOP_11811 Mukilteo Speedway 110')
os.rename('C:/Users/brandonh/Desktop/Pretreatment Inspections/204 Lincoln Av','C:/Users/brandonh/Desktop/Pretreatment Inspections/WHIDBEY COFFEE _204 Lincoln Av')
os.rename('C:/Users/brandonh/Desktop/Pretreatment Inspections/2916 100th St SW','C:/Users/brandonh/Desktop/Pretreatment Inspections/plating Company_2916 100th St SW')
os.rename('C:/Users/brandonh/Desktop/Pretreatment Inspections/304 Lincoln Av','C:/Users/brandonh/Desktop/Pretreatment Inspections/ROSEHILL COMMUNITY CENTER_304 Lincoln Av')
os.rename('C:/Users/brandonh/Desktop/Pretreatment Inspections/3100 112th St SW','C:/Users/brandonh/Desktop/Pretreatment Inspections/Boeing_3100 112th St SW')
os.rename('C:/Users/brandonh/Desktop/Pretreatment Inspections/3121 109th St SW','C:/Users/brandonh/Desktop/Pretreatment Inspections/ATS_3121 109th St SW')
os.rename('C:/Users/brandonh/Desktop/Pretreatment Inspections/315 Lincoln Av','C:/Users/brandonh/Desktop/Pretreatment Inspections/Voke Dental_315 Lincoln Av')
os.rename('C:/Users/brandonh/Desktop/Pretreatment Inspections/3407 109th St SW','C:/Users/brandonh/Desktop/Pretreatment Inspections/Flying Heritage_3407 109th St SW')
os.rename('C:/Users/brandonh/Desktop/Pretreatment Inspections/3511 132nd St SW 100','C:/Users/brandonh/Desktop/Pretreatment Inspections/Pristine enviro services_3511 132nd St SW 100')
os.rename('C:/Users/brandonh/Desktop/Pretreatment Inspections/403 Lincoln Av','C:/Users/brandonh/Desktop/Pretreatment Inspections/SULLYS_403 Lincoln Av')
os.rename('C:/Users/brandonh/Desktop/Pretreatment Inspections/407 Lincoln Av','C:/Users/brandonh/Desktop/Pretreatment Inspections/MUKILTEO CHOCOLATE CO_407 Lincoln Av')
os.rename('C:/Users/brandonh/Desktop/Pretreatment Inspections/415 Lincoln Av','C:/Users/brandonh/Desktop/Pretreatment Inspections/AMBROSIA_415 Lincoln Av')
os.rename('C:/Users/brandonh/Desktop/Pretreatment Inspections/4201 Russell Rd 1','C:/Users/brandonh/Desktop/Pretreatment Inspections/Workforce_4201 Russell Rd 1')
os.rename('C:/Users/brandonh/Desktop/Pretreatment Inspections/4204 Russell Rd F','C:/Users/brandonh/Desktop/Pretreatment Inspections/aculine_4204 Russell Rd F')
os.rename('C:/Users/brandonh/Desktop/Pretreatment Inspections/4204 Russell Rd P, Q, R','C:/Users/brandonh/Desktop/Pretreatment Inspections/industrial plating corp_4204 Russell Rd P, Q, R')
os.rename('C:/Users/brandonh/Desktop/Pretreatment Inspections/4208 Russell Rd A','C:/Users/brandonh/Desktop/Pretreatment Inspections/Silver hoarde fishing supplies_4208 Russell Rd A')
os.rename('C:/Users/brandonh/Desktop/Pretreatment Inspections/4208 Russell Rd K','C:/Users/brandonh/Desktop/Pretreatment Inspections/advanced prototype tech_4208 Russell Rd K')
os.rename('C:/Users/brandonh/Desktop/Pretreatment Inspections/4212 Russell Rd A','C:/Users/brandonh/Desktop/Pretreatment Inspections/METRON METAL FINISHING INC_4212 Russell Rd A')
os.rename('C:/Users/brandonh/Desktop/Pretreatment Inspections/4212 Russell Rd M','C:/Users/brandonh/Desktop/Pretreatment Inspections/TERRENE ENGINEERING INC_4212 Russell Rd M')
os.rename('C:/Users/brandonh/Desktop/Pretreatment Inspections/4216 Russell Rd','C:/Users/brandonh/Desktop/Pretreatment Inspections/APPLIED FINISHING_4216 Russell Rd')
os.rename('C:/Users/brandonh/Desktop/Pretreatment Inspections/4220 Russell Rd','C:/Users/brandonh/Desktop/Pretreatment Inspections/CLASSIC MOTORSPORTS_4220 Russell Rd')
os.rename('C:/Users/brandonh/Desktop/Pretreatment Inspections/4314 Russell Rd 101','C:/Users/brandonh/Desktop/Pretreatment Inspections/BRANCH SOLUTIONS_4314 Russell Rd 101')
os.rename('C:/Users/brandonh/Desktop/Pretreatment Inspections/4314 Russell Rd 103','C:/Users/brandonh/Desktop/Pretreatment Inspections/THE VORTEX_4314 Russell Rd 103')
os.rename('C:/Users/brandonh/Desktop/Pretreatment Inspections/4329 Chennault Beach Rd','C:/Users/brandonh/Desktop/Pretreatment Inspections/TRAXX _4329 Chennault Beach Rd')
os.rename('C:/Users/brandonh/Desktop/Pretreatment Inspections/4400 Chennault Beach Rd','C:/Users/brandonh/Desktop/Pretreatment Inspections/COMPLEX_4400 Chennault Beach Rd')
os.rename('C:/Users/brandonh/Desktop/Pretreatment Inspections/4400 Chennault Beach Rd E','C:/Users/brandonh/Desktop/Pretreatment Inspections/BULLDOG POWDER COATING_4400 Chennault Beach Rd E')
os.rename('C:/Users/brandonh/Desktop/Pretreatment Inspections/4403 Russell Rd 108','C:/Users/brandonh/Desktop/Pretreatment Inspections/PETRO-CHEM_4403 Russell Rd 108')
os.rename('C:/Users/brandonh/Desktop/Pretreatment Inspections/4403 Russell Rd 110','C:/Users/brandonh/Desktop/Pretreatment Inspections/American rifle company_4403 Russell Rd 110')
os.rename('C:/Users/brandonh/Desktop/Pretreatment Inspections/4403 Russell Rd 114','C:/Users/brandonh/Desktop/Pretreatment Inspections/LEGENDS ROOFING CO INC_4403 Russell Rd 114')
os.rename('C:/Users/brandonh/Desktop/Pretreatment Inspections/4403 Russell Rd 116','C:/Users/brandonh/Desktop/Pretreatment Inspections/ICG COMPANY_4403 Russell Rd 116')
os.rename('C:/Users/brandonh/Desktop/Pretreatment Inspections/4403 Russell Rd 118','C:/Users/brandonh/Desktop/Pretreatment Inspections/GLASS GARDENS NW LLC_4403 Russell Rd 118')
os.rename('C:/Users/brandonh/Desktop/Pretreatment Inspections/4407 106th St SW','C:/Users/brandonh/Desktop/Pretreatment Inspections/Fam dental/oral surgery_4407 106th St SW')
os.rename('C:/Users/brandonh/Desktop/Pretreatment Inspections/4407 106th St SW B','C:/Users/brandonh/Desktop/Pretreatment Inspections/HARBOUR PT ORAL/SURGERY_4407 106th St SW B')
os.rename('C:/Users/brandonh/Desktop/Pretreatment Inspections/4412 Russell Rd A','C:/Users/brandonh/Desktop/Pretreatment Inspections/PRODUCTION PLATING_4412 Russell Rd A')
os.rename('C:/Users/brandonh/Desktop/Pretreatment Inspections/4413 Chennault Beach Rd A','C:/Users/brandonh/Desktop/Pretreatment Inspections/ELECTROIMPACT_4413 Chennault Beach Rd A')
os.rename('C:/Users/brandonh/Desktop/Pretreatment Inspections/4416 Russell Rd A','C:/Users/brandonh/Desktop/Pretreatment Inspections/POLAR BEAR ENERGY SOLUTIONS_4416 Russell Rd A')
os.rename('C:/Users/brandonh/Desktop/Pretreatment Inspections/4416 Russell Rd B','C:/Users/brandonh/Desktop/Pretreatment Inspections/PLEXUS MANUFACTURING INC_4416 Russell Rd B')
os.rename('C:/Users/brandonh/Desktop/Pretreatment Inspections/4420 106th St SW','C:/Users/brandonh/Desktop/Pretreatment Inspections/KIDS DENTISTRY MUKILTEO_4420 106th St SW')
os.rename('C:/Users/brandonh/Desktop/Pretreatment Inspections/4420 Russell Rd A','C:/Users/brandonh/Desktop/Pretreatment Inspections/MANUFACTURING & DESIGN - MDI_4420 Russell Rd A')
os.rename('C:/Users/brandonh/Desktop/Pretreatment Inspections/4420 Russell Rd B','C:/Users/brandonh/Desktop/Pretreatment Inspections/D & D WELDING_4420 Russell Rd B')
os.rename('C:/Users/brandonh/Desktop/Pretreatment Inspections/4430 106th St SW','C:/Users/brandonh/Desktop/Pretreatment Inspections/Everett clinic_4430 106th St SW')
os.rename('C:/Users/brandonh/Desktop/Pretreatment Inspections/4433 Russell Rd 102','C:/Users/brandonh/Desktop/Pretreatment Inspections/HENDERSON ENTERPRISES, INC_4433 Russell Rd 102')
os.rename('C:/Users/brandonh/Desktop/Pretreatment Inspections/4433 Russell Rd 110','C:/Users/brandonh/Desktop/Pretreatment Inspections/APPLIED POWER AND CONTROL_4433 Russell Rd 110')
os.rename('C:/Users/brandonh/Desktop/Pretreatment Inspections/4433 Russell Rd 111','C:/Users/brandonh/Desktop/Pretreatment Inspections/Restoration Envy_4433 Russell Rd 111')
os.rename('C:/Users/brandonh/Desktop/Pretreatment Inspections/4433 Russell Rd 113','C:/Users/brandonh/Desktop/Pretreatment Inspections/GROUCHY CHEF_4433 Russell Rd 113')
os.rename('C:/Users/brandonh/Desktop/Pretreatment Inspections/4463 Russell Rd 101','C:/Users/brandonh/Desktop/Pretreatment Inspections/STONEWOOD DESIGN INC_4463 Russell Rd 101')
os.rename('C:/Users/brandonh/Desktop/Pretreatment Inspections/4463 Russell Rd 103','C:/Users/brandonh/Desktop/Pretreatment Inspections/RESTOR FX_4463 Russell Rd 103')
os.rename('C:/Users/brandonh/Desktop/Pretreatment Inspections/4463 Russell Rd 105','C:/Users/brandonh/Desktop/Pretreatment Inspections/GOULD SOUTHERN_4463 Russell Rd 105')
os.rename('C:/Users/brandonh/Desktop/Pretreatment Inspections/4470 Chennault Beach Rd','C:/Users/brandonh/Desktop/Pretreatment Inspections/WESTAR MEDICAL PRODUCTS_4470 Chennault Beach Rd')
os.rename('C:/Users/brandonh/Desktop/Pretreatment Inspections/4480 Chennault Beach Rd','C:/Users/brandonh/Desktop/Pretreatment Inspections/HIMALAYAN DOG CHEW - MAILING ADD_4480 Chennault Beach Rd')
os.rename('C:/Users/brandonh/Desktop/Pretreatment Inspections/4493 Russell Rd D','C:/Users/brandonh/Desktop/Pretreatment Inspections/str8 sheet_4493 Russell Rd D')
os.rename('C:/Users/brandonh/Desktop/Pretreatment Inspections/4493 Russell Rd E','C:/Users/brandonh/Desktop/Pretreatment Inspections/DIVE XTRAS/CLARO WORKS_4493 Russell Rd E')
os.rename('C:/Users/brandonh/Desktop/Pretreatment Inspections/4493 Russell Rd F','C:/Users/brandonh/Desktop/Pretreatment Inspections/MARROTT DENTAL_4493 Russell Rd F')
os.rename('C:/Users/brandonh/Desktop/Pretreatment Inspections/4493 Russell Rd G','C:/Users/brandonh/Desktop/Pretreatment Inspections/MAZZA COFFEE COMPANY LLC_4493 Russell Rd G')
os.rename('C:/Users/brandonh/Desktop/Pretreatment Inspections/4493 Russell Rd H','C:/Users/brandonh/Desktop/Pretreatment Inspections/425 AUTO BODY AND PAINT_4493 Russell Rd H')
os.rename('C:/Users/brandonh/Desktop/Pretreatment Inspections/4520 107th St SW','C:/Users/brandonh/Desktop/Pretreatment Inspections/PACIFIC SEAFOOD CO_4520 107th St SW')
os.rename('C:/Users/brandonh/Desktop/Pretreatment Inspections/4600 116th St SW','C:/Users/brandonh/Desktop/Pretreatment Inspections/WIZARD INTERNATIONAL_4600 116th St SW')
os.rename('C:/Users/brandonh/Desktop/Pretreatment Inspections/4602 Chennault Beach Rd A1, B1, B2','C:/Users/brandonh/Desktop/Pretreatment Inspections/DIAMOND KNOT BREWING CO_4602 Chennault Beach Rd A1, B1, B2')
os.rename('C:/Users/brandonh/Desktop/Pretreatment Inspections/4602 Chennault Beach Rd A2','C:/Users/brandonh/Desktop/Pretreatment Inspections/CASCADE BOILER SERVICES INC_4602 Chennault Beach Rd A2')
os.rename('C:/Users/brandonh/Desktop/Pretreatment Inspections/4602 Chennault Beach Rd C2','C:/Users/brandonh/Desktop/Pretreatment Inspections/PACIFIC GLASS & DOOR INC_4602 Chennault Beach Rd C2')
os.rename('C:/Users/brandonh/Desktop/Pretreatment Inspections/4602 Chennault Beach Rd D','C:/Users/brandonh/Desktop/Pretreatment Inspections/AERO MAC, INC._4602 Chennault Beach Rd D')
os.rename('C:/Users/brandonh/Desktop/Pretreatment Inspections/4617 Chennault Beach Rd','C:/Users/brandonh/Desktop/Pretreatment Inspections/CR ENTERPRISES_4617 Chennault Beach Rd')
os.rename('C:/Users/brandonh/Desktop/Pretreatment Inspections/4625 Chennault Beach Rd','C:/Users/brandonh/Desktop/Pretreatment Inspections/TESCO CORP_4625 Chennault Beach Rd')
os.rename('C:/Users/brandonh/Desktop/Pretreatment Inspections/4710 116th St SW','C:/Users/brandonh/Desktop/Pretreatment Inspections/SATCO PRODUCTS OF WASHINGTON_4710 116th St SW')
os.rename('C:/Users/brandonh/Desktop/Pretreatment Inspections/4901 81st St SW','C:/Users/brandonh/Desktop/Pretreatment Inspections/MUKILTEO SMILES_4901 81st St SW')
os.rename('C:/Users/brandonh/Desktop/Pretreatment Inspections/613 5th St','C:/Users/brandonh/Desktop/Pretreatment Inspections/THE SYDNEY BAKERY_613 5th St')
os.rename('C:/Users/brandonh/Desktop/Pretreatment Inspections/621 Front St','C:/Users/brandonh/Desktop/Pretreatment Inspections/DIAMOND KNOT BREWERY_621 Front St')
os.rename('C:/Users/brandonh/Desktop/Pretreatment Inspections/6500 Harbour Heights Parkway','C:/Users/brandonh/Desktop/Pretreatment Inspections/THE BOEING COMPANY_6500 Harbour Heights Parkway')
os.rename('C:/Users/brandonh/Desktop/Pretreatment Inspections/710 Front St','C:/Users/brandonh/Desktop/Pretreatment Inspections/IVARS FISH BAR_710 Front St')
os.rename('C:/Users/brandonh/Desktop/Pretreatment Inspections/714 2nd St','C:/Users/brandonh/Desktop/Pretreatment Inspections/ARNIES RESTAURANT _714 2nd St')
os.rename('C:/Users/brandonh/Desktop/Pretreatment Inspections/7911 44th Av W','C:/Users/brandonh/Desktop/Pretreatment Inspections/NEW TECH INDUSTRIES_7911 44th Av W')
os.rename('C:/Users/brandonh/Desktop/Pretreatment Inspections/7924 40th Av W','C:/Users/brandonh/Desktop/Pretreatment Inspections/WESTERN SPECIALTIES CO_7924 40th Av W')
os.rename('C:/Users/brandonh/Desktop/Pretreatment Inspections/7928 Mukilteo Speedway 101','C:/Users/brandonh/Desktop/Pretreatment Inspections/MUKILTEO LODGE_7928 Mukilteo Speedway 101')
os.rename('C:/Users/brandonh/Desktop/Pretreatment Inspections/7928 Mukilteo Speedway 201','C:/Users/brandonh/Desktop/Pretreatment Inspections/MUKILTEO DENTAL CENTER_7928 Mukilteo Speedway 201')
os.rename('C:/Users/brandonh/Desktop/Pretreatment Inspections/7929 44th Av W - A,G','C:/Users/brandonh/Desktop/Pretreatment Inspections/OMEGA PRECISION_7929 44th Av W - A,G')
os.rename('C:/Users/brandonh/Desktop/Pretreatment Inspections/7929 44th Av W - C','C:/Users/brandonh/Desktop/Pretreatment Inspections/CONAGGBIT INC_7929 44th Av W - C')
os.rename('C:/Users/brandonh/Desktop/Pretreatment Inspections/8004 Mukilteo Speedway 7','C:/Users/brandonh/Desktop/Pretreatment Inspections/Sound family dentistry_8004 Mukilteo Speedway 7')
os.rename('C:/Users/brandonh/Desktop/Pretreatment Inspections/8004 Mukilteo Speedway 8','C:/Users/brandonh/Desktop/Pretreatment Inspections/AMICI ITALIAN BISTRO_8004 Mukilteo Speedway 8')
os.rename('C:/Users/brandonh/Desktop/Pretreatment Inspections/801 2nd St','C:/Users/brandonh/Desktop/Pretreatment Inspections/EMPTY - LA CASCADA ACAPULCO_801 2nd St')
os.rename('C:/Users/brandonh/Desktop/Pretreatment Inspections/802 Front St','C:/Users/brandonh/Desktop/Pretreatment Inspections/noaa_802 Front St')
os.rename('C:/Users/brandonh/Desktop/Pretreatment Inspections/8203 Mukilteo Speedway','C:/Users/brandonh/Desktop/Pretreatment Inspections/THE SPOT (CARWASH/RESTAURANT)_8203 Mukilteo Speedway')
os.rename('C:/Users/brandonh/Desktop/Pretreatment Inspections/8227 44th Av W','C:/Users/brandonh/Desktop/Pretreatment Inspections/Paul Yetter_8227 44th Av W')
os.rename('C:/Users/brandonh/Desktop/Pretreatment Inspections/8229 44th Av W C','C:/Users/brandonh/Desktop/Pretreatment Inspections/KINGS TERIYAKI_8229 44th Av W C')
os.rename('C:/Users/brandonh/Desktop/Pretreatment Inspections/8307 Mukilteo Speedway','C:/Users/brandonh/Desktop/Pretreatment Inspections/ZS BURGER _8307 Mukilteo Speedway')
os.rename('C:/Users/brandonh/Desktop/Pretreatment Inspections/8326 Mukilteo Speedway','C:/Users/brandonh/Desktop/Pretreatment Inspections/BROOKLYN BROTHERS PIZZA_8326 Mukilteo Speedway')
os.rename('C:/Users/brandonh/Desktop/Pretreatment Inspections/833 2nd St','C:/Users/brandonh/Desktop/Pretreatment Inspections/MUKILTEO FAMILY DENTISTRY_833 2nd St')
os.rename('C:/Users/brandonh/Desktop/Pretreatment Inspections/8401 Mukilteo Speedway','C:/Users/brandonh/Desktop/Pretreatment Inspections/TACO BELL_8401 Mukilteo Speedway')
os.rename('C:/Users/brandonh/Desktop/Pretreatment Inspections/8410 Mukilteo Speedway B','C:/Users/brandonh/Desktop/Pretreatment Inspections/SABOR A MEXICO / LA JOYA LLC_8410 Mukilteo Speedway B')
os.rename('C:/Users/brandonh/Desktop/Pretreatment Inspections/8490 Mukilteo Speedway 100','C:/Users/brandonh/Desktop/Pretreatment Inspections/KONETCHY BODY SPA_8490 Mukilteo Speedway 100')
os.rename('C:/Users/brandonh/Desktop/Pretreatment Inspections/9600 Harbour Pl','C:/Users/brandonh/Desktop/Pretreatment Inspections/STAYBRIDGE HOTEL_9600 Harbour Pl')
os.rename('C:/Users/brandonh/Desktop/Pretreatment Inspections/9700 Harbour Place 114','C:/Users/brandonh/Desktop/Pretreatment Inspections/Architextures_9700 Harbour Place 114')
os.rename('C:/Users/brandonh/Desktop/Pretreatment Inspections/9700 Harbour Place 217','C:/Users/brandonh/Desktop/Pretreatment Inspections/STRUCTURAL INTEGRITY ENG, INC_9700 Harbour Place 217')
os.rename('C:/Users/brandonh/Desktop/Pretreatment Inspections/9700 Harbour Place 223','C:/Users/brandonh/Desktop/Pretreatment Inspections/APACHE AEROSPACE INC_9700 Harbour Place 223')
os.rename('C:/Users/brandonh/Desktop/Pretreatment Inspections/9800 Harbour Pl 203','C:/Users/brandonh/Desktop/Pretreatment Inspections/HARBOUR PLACE DENTAL_9800 Harbour Pl 203')
os.rename('C:/Users/brandonh/Desktop/Pretreatment Inspections/9800 Harbour Place 200','C:/Users/brandonh/Desktop/Pretreatment Inspections/LYNNS SEWING_9800 Harbour Place 200')
os.rename('C:/Users/brandonh/Desktop/Pretreatment Inspections/9999 Harbour Pl 100','C:/Users/brandonh/Desktop/Pretreatment Inspections/BLU BURGERS & BREW_9999 Harbour Pl 100')
os.rename('C:/Users/brandonh/Desktop/Pretreatment Inspections/9999 Harbour Pl 102','C:/Users/brandonh/Desktop/Pretreatment Inspections/SUBWAY #22618_9999 Harbour Pl 102')
os.rename('C:/Users/brandonh/Desktop/Pretreatment Inspections/9999 Harbour Place 105','C:/Users/brandonh/Desktop/Pretreatment Inspections/CAFÉ SOLEIL_9999 Harbour Place 105')
